### ISSUE TITLE
YAMLLoadWarning

### ISSUE THREAD

**Issue by Phil-ThePower-Pearce** [cvandeplas/pystemon#103]
When running in python3

> pystemon.py:1391: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  yamlconfig = yaml.load(open(configfile))

**Comment by BeRambo** [comment]
This fixed the error for me:

`yamlconfig = yaml.load(open(configfile), Loader=yaml.FullLoader)`

**Comment by cvandeplas** [comment]
Thank you, this is resolved
