### ISSUE TITLE
AttributeError: 'list' object has no attribute 'add'

### ISSUE THREAD

**Issue by jalewis** [cvandeplas/pystemon#105]
AttributeError: 'list' object has no attribute 'add'

https://github.com/cvandeplas/pystemon/blob/master/pystemon.py#L881

I changed from add to append and it works, I'm not sure if the error is specific to me or only visible when proxies are enabled. I'll submit a PR if that's preferred.

proxies_list.append(line)

**Comment by cvandeplas** [comment]
nice catch. it's corrected now. thank you very much !
