### ISSUE TITLE
sleep time between download of pasties

### ISSUE THREAD

**Issue by cvandeplas** [cvandeplas/pystemon#16]
Allow some dynamic sleep time between the download of the pasties.
Related to #15 stats of queues so the user can see if his sleep timings are letting the queue grow indefinitely

**Comment by certxlm** [comment]
Hello,
We have a working PR to fix these issue: #106 
We also have another PR ready to support HTTP status 429 (too many requests).

And we just started working on modularizing pystemon. The goal of this big PR would be to move the specific Pastie* classes out of the main code:

1. to be able to download the needed classes dynamically
2. to support our own private sites without having to modify the main code. 

If this last PR can be of interrested for you, please let us know, as it is going to be a large refactoring of the code...

Regards,
CERT-XLM

**Comment by cvandeplas** [comment]
Interesting, thank you very much ! 
Modularizing the `Pastie*` classes in separate files is definitely a great idea. I assume you meant "loading" the needed classes dynamically. 
Please be careful with that part of the code, we don't want to introduce vulnerabilities.

**Comment by certxlm** [comment]
Ah, yep, of course, we meant loading, not downloading, sorry for the typo.

We planned two global steps for the modularization. First split the whole project into its logical parts.
For example, we already have working code with the proxy part outside of the main pystemon.py:
- https://github.com/certxlm/pystemon/tree/modularize

Once we have a better handling on the various components, use **_importlib_** to load the pastie classes from the pastie subdirectory, hopefully bounding it to this very specific directory. But that's for latter, when the first global step is definitely clean and working.
