### ISSUE TITLE
Weird Output

### ISSUE THREAD

**Issue by Trig0n** [cvandeplas/pystemon#28]
![](http://i.imgur.com/1bLAfnu.png)

Also fucks up my console prompt.
![](http://i.imgur.com/QpCPNzy.png)

Sometime happens to be completely unresponsive and I have to killall python.
Bug or Feature?

**Comment by cvandeplas** [comment]
Very interesting. This is the first time this behavior is reported.
It could be a feature for people who like to type <code>stty sane</code>, but for myself I see this as a bug.

Could you share the following:
- how often does this happens? minutes, days, weeks, months?
- with what parameters are you launching pystemon? 
- could you share your configuration? If needed privately.

**Comment by Trig0n** [comment]
I've disabled the pastebin pro feature, now it runs without Problems.
Else it happened every ~5 minutes.
Happened with '-v' and without. Didn't really make a difference.

Config: http://pastebin.com/RuFGGPi8
(How ironic, posting it on pastebin.)

**Comment by cvandeplas** [comment]
thanks for the details, I'll try to reproduce it.

**Comment by Trig0n** [comment]
http://pastebin.com/kfpsi2q1
New config, which makes it work just fine.
No errors or any html code in the output.
Just for you, so you might see what might have caused the problem.

**Comment by cvandeplas** [comment]
Are you still having this problem? 
I was not able to reproduce it.

**Comment by Trig0n** [comment]
Not with this config: http://pastebin.com/kfpsi2q1
Tbh I did not use it the past few weeks.
But last time I tried it, it worked with that config.
Also @Beercow has a quiet nice config with alot of sites. (Hadn't had problems with his config too.)
