### ISSUE TITLE
pystemon not searching pastebin.com

### ISSUE THREAD

**Issue by ksystemsio** [cvandeplas/pystemon#29]
Hi. Your tool is just great, but I am encountering a problem:

If I try to search for some specific patterns, I get errors from slexy.org which I do not get while using other patterns: 

[2015-11-21 20:17:34,760] Found 21 new pasties for site snipt.net. There are now 20 pasties to be downloaded.
[2015-11-21 20:17:36,885] Found hit for ['--------'] in pastie http://slexy.org/raw/s2SNyQD6FM
[2015-11-21 20:17:36,887] ThreadPasties for slexy.org crashed unexpectectly, recovering...: 'ascii' codec can't encode characters in position 1171-1172: ordinal not in range(128)
[2015-11-21 20:17:38,810] Found hit for ['---------'] in pastie http://slexy.org/raw/s21C3nxB2v
[2015-11-21 20:17:38,811] ThreadPasties for slexy.org crashed unexpectectly, recovering...: 'ascii' codec can't encode characters in position 1171-1172: ordinal not in range(128)

And, most important, I get absolutely no results from pastebin.com, no matter what the pattern is.

I am behind TOR thru "delegated" daemon.

Thanks

**Comment by Julznova** [comment]
Hey, thanks so much for your great tool. Been having the same issue for over a week now (re: pastebin). I'll supply log asap

**Comment by cvandeplas** [comment]
About pastebin:
- are you using pastebin or the pro version with API key? 
- the basic edition works for me (see below), so I wonder it you don't have badly written regexes. Could you share your config file?  (privately if needed)
```
[2015-11-22 07:47:04,159] Found 8 new pasties for site pastebin.com. There are now 8 pasties to be downloaded.
[2015-11-22 07:47:04,464] Found hit for ['[^a-zA-Z0-9]example\\.com'] in pastie http://pastebin.com/raw.php?i=E1VqmJ5v
```

About slexy, the error you have is related to character-set encoding. This is unexpected as I believed we fixed all these.  
Am I understanding you correctly that you only get this with specific search pattens?  Could you share the config (privately if needed)?  Without that I can't reproduce it.

**Comment by turtle977** [comment]
Hi, I am just using pastebin.com (no API). Today I am getting something different:

[2015-11-22 12:46:01,138] Found 2 new pasties for site paste.frubar.net. There are now 3 pasties to be downloaded.
[2015-11-22 12:46:01,139] ThreadPasties for pastebin.fr crashed unexpectectly, recovering...: 'search'
[2015-11-22 12:46:01,139] ThreadPasties for snipt.net crashed unexpectectly, recovering...: 'search'
[2015-11-22 12:46:01,344] Downloading list of new pastes from paste.lisp.org. Will check again in 10 seconds
[2015-11-22 12:46:01,345] ThreadPasties for lpaste.net crashed unexpectectly, recovering...: 'search'
[2015-11-22 12:46:01,346] ThreadPasties for ideone.com crashed unexpectectly, recovering...: 'search'
[2015-11-22 12:46:01,347] ThreadPasties for kickasspastes.com crashed unexpectectly, recovering...: 'search'
[2015-11-22 12:46:01,363] ThreadPasties for paste.opensuse.org crashed unexpectectly, recovering...: 'search'
[2015-11-22 12:46:01,366] ThreadPasties for paste.kde.org crashed unexpectectly, recovering...: 'search'
[2015-11-22 12:46:01,449] ThreadPasties for kpaste.net crashed unexpectectly, recovering...: 'search'
[2015-11-22 12:46:01,522] Downloading list of new pastes from pastebin.fr. Will check again in 24 seconds
[2015-11-22 12:46:01,560] ThreadPasties for kickasspastes.com crashed unexpectectly, recovering...: 'search'
[2015-11-22 12:46:01,573] ThreadPasties for lpaste.net crashed unexpectectly, recovering...: 'search'

Here is my pystemon.yaml:


#network:               # Network settings
#  ip: '1.1.1.1'        # Specify source IP address if you want to bind on a specific one

syslog:
  enable: yes           # enable syslog

archive:
  save: yes             # Keep
  save-all: no          # Keep a copy of all pasties
  dir: "alerts"         # Directory where matching pasties should be kept
  dir-all: "archive"    # Directory where all pasties should be kept (if save-all is set to yes)
  compress: yes         # Store the pasties compressed

db:
  sqlite3:              # Store information about the pastie in a database
    enable: no          # Activate this DB engine   # NOT FULLY IMPLEMENTED
    file: 'db.sqlite3'  # The filename of the database

redis:
  queue: no
  server: "localhost"
  port: 6379
  database: 10

email:
  alert: yes             # Enable/disable email alerts
  from: alert@localhost
  to: m.levy@tps-srl.net
  server: 127.0.0.1     # Address of the server (hostname or IP)
  port: 25              # Outgoing SMTP port: 25, 587, ...
  username: ''          # (optional) Username for authentication. Leave blank for no authentication.
  password: ''          # (optional) Password for authentication. Leave blank for no authentication.
  subject: '[pystemon] - {subject}'

#####
# Definition of regular expressions to search for in the pasties
#
search:
#  - description: ''    # (optional) A human readable description. (used in alerting)
#    search: ''         # The regular expression to search for
#    count: ''          # (optional) How many hits should it have to be interesting?
#    exclude: ''        # (optional) Do not alert if this regular expression matches
#    regex-flags: ''    # (optional) Regular expression flags to give to the find function.
#                       #            Default = re.IGNORECASE
#                       #            Set to 0 to have no flags set
#                       #            See http://docs.python.org/2/library/re.html#re.DEBUG for more info.
#                       #            Warning: when setting this the default is overridden
#                       #  example: 're.MULTILINE + re.DOTALL + re.IGNORECASE'
#    to: ''             # (optional) Additional recipients for email alert, comma separated list

  - search: 'test'
#  - search: '[^a-zA-Z0-9]foobar\.com'
  - description: 'test'

#####
# Configuration section for the paste sites
#
threads: 1              # number of download threads per site
site:
#  example.com:
#    archive-url:       # the url where the list of last pasties is present
#                       # example: 'http://pastebin.com/archive'
#    archive-regex:     # a regular expression to extract the pastie-id from the page.
#                       # do not forget the () to extract the pastie-id
#                       # example: '<a href="/(\w{8})">.+</a></td>'
#    download-url:      # url for the raw pastie.
#                       # Should contain {id} on the place where the ID of the pastie needs to be placed
#                       # example: 'http://pastebin.com/raw.php?i={id}'
#    update-max: 40     # every X seconds check for new updates to see if new pasties are available
#    update-min: 30     # a random number will be chosen between these two numbers
#    pastie-classname:  # OPTIONAL: The name of a custom Class that inherits from Pastie
#                       # This is practical for sites that require custom fetchPastie() functions

  pastebin.com:
    archive-url: 'http://pastebin.com/archive'
    archive-regex: '<a href="/(\w{8})">.+</a></td>'
    download-url: 'http://pastebin.com/raw.php?i={id}'
    update-max: 95
    update-min: 85

# See https:/pastebin.com/api_scraping_faq , you will need a pro accout on pastebin
#  pastebin.com_pro:
#    archive-url: 'http://pastebin.com/api_scraping.php?linmit=500'
#    archive-regex: '"key": "(.+)",'
#    download-url: 'http://pastebin.com/api_scrape_item.php?i={id}'
#    update-max: 50
#    update-min: 40

  pastie.org:
    archive-url: 'http://pastie.org/pastes'
    archive-regex: '<a href="http://pastie.org/pastes/(\d+)">'
    download-url: 'http://pastie.org/pastes/{id}/text'

  slexy.org:
    archive-url: 'http://slexy.org/recent/'
    archive-regex: '<a href="/view/([a-zA-Z0-9]+)">View paste</a>'
    download-url: 'http://slexy.org/raw/{id}'

  gist.github.com:
    archive-url: 'https://gist.github.com/discover'
    archive-regex: '<a href="/([a-zA-Z0-9]+/[a-z0-9]+)">'
    download-url: 'https://gist.githubusercontent.com/{id}/raw'

  codepad.org:
    archive-url: 'http://codepad.org/recent'
    archive-regex: '<a href="http://codepad.org/([a-zA-Z0-9]+)">view'
    download-url: 'http://codepad.org/{id}/raw.txt'

  snipt.net:
    pastie-classname: PastieSniptNet
    archive-url: 'https://snipt.net/public/?rss'
    archive-regex: '<link>https://snipt.net/(.+)/</link>'
    download-url: 'https://snipt.net/{id}/'

#  safebin.net:  # FIXME not finished
#    archive-url: 'http://safebin.net/?archive'
#    archive-regex: '<a title="[a-zA-Z0-9 :,]+" href="/([0-9]+)">'
#    download-url: 'http://safebin.net/{id}'
#    update-max: 60
#    update-min: 50

  kickasspastes.com:
    archive-url: 'http://kickasspastes.com/archive.php'
    archive-regex: '<td><a href="/(\d+)'
    download-url: 'http://kickasspastes.com/{id}'

  paste.frubar.net:
    archive-url: 'http://paste.frubar.net/'
    archive-regex: '<a href="http://paste.frubar.net/(\d+)'
    download-url: 'http://paste.frubar.net/{id}'

  pastebin.ca:
    archive-url: 'http://pastebin.ca'
    archive-regex: 'rel="/preview.php\?id=(\d+)'
    download-url: 'http://pastebin.ca/{id}'

  ideone.com:
    archive-url: 'http://ideone.com/recent'
    archive-regex: '<a href="/([a-zA-Z0-9]+)">#'
    download-url: 'http://ideone.com/plain/{id}'

  justpaste.it:
    archive-url: 'https://justpaste.it/topall'
    archive-regex: '<a href="https://justpaste.it/([a-zA-Z0-9]+)">'
    download-url: 'https://justpaste.it/{id}'

  paste.org.ru:
    archive-url: 'http://paste.org.ru'
    archive-regex: '<a href=''/\?(\w+)''>'
    download-url: 'http://paste.org.ru/?{id}'

  paste.lisp.org:
    archive-url: 'http://paste.lisp.org'
    archive-regex: '<a href="http://paste.lisp.org/display/(\d+)"'
    download-url: 'http://paste.lisp.org/display/{id}'

  www.linkpaste.com:
    archive-url: 'http://www.linkpaste.com/last-pastes.html'
    archive-regex: '<a href="http://www.linkpaste.com/(\w+)">'
    download-url: 'http://www.linkpaste.com/{id}'

  snipplr.com:
    archive-url: 'http://snipplr.com/all'
    archive-regex: '<a href=''/view/(.+?/.+?/)'
    download-url: 'http://snipplr.com/view/{id}'

  lpaste.net:
    archive-url: 'http://lpaste.net/browse'
    archive-regex: '<a href="/(\d+)"'
    download-url: 'http://lpaste.net/raw/{id}'

  wklej.se:
    archive-url: 'http://wklej.se'
    archive-regex: '<a href="http://users.wklej.se/(.+?/.+?")'
    download-url: 'http://wklej.se/{id}'

  pastebin.ru:
    archive-url: 'http://pastebin.ru/'
    archive-regex: '<a href="/(\w+)">'
    download-url: 'http://pastebin.ru/{id}'

  pastebin.gr:
    archive-url: 'http://pastebin.gr/'
    archive-regex: '<a href="http://pastebin.gr/(\d+)'
    download-url: 'http://pastebin.gr/pastebin.php?dl={id}'

  pastebin.fr:
    archive-url: 'http://pastebin.fr'
    archive-regex: '<a href="http://pastebin.fr/(\d+)'
    download-url: 'http://pastebin.fr/{id}'

  paste.opensuse.org:
    archive-url: 'http://paste.opensuse.org/lists'
    archive-regex: '<a href="http://paste.opensuse.org/(\d+)'
    download-url: 'http://paste.opensuse.org/view/raw/{id}'

  paste.kde.org:
    archive-url: 'https://paste.kde.org/all'
    archive-regex: '<a href="https://paste.kde.org/(\w+)" c'
    download-url: 'https://paste.kde.org/{id}'

  paste.fedoraproject.org:
    archive-url: 'http://paste.fedoraproject.org/all/'
    archive-regex: '<a href="/(\d+)/'
    download-url: 'http://paste.fedoraproject.org/{id}/raw/'

  paste.debian.net:
    archive-url: 'http://paste.debian.net/'
    archive-regex: '<a href=''//paste.debian.net/(\d+)'
    download-url: 'http://paste.debian.net/plain/{id}'

  kpaste.net:
    archive-url: 'http://kpaste.net/'
    archive-regex: '" href="/(\w+)">'
    download-url: 'http://kpaste.net/{id}?raw'

  pastebay.org:
    archive-url: 'http://pastebay.org/index.php/lists'
    archive-regex: '<a href="http://pastebay.org/index.php/view/(\d+)'
    download-url: 'http:pastebay.org/index.php/view/raw/{id}'

# TODO
# http://www.safebin.net/       # more complex site
# http://www.heypasteit.com/    # http://www.heypasteit.com/clip/0IZA => incremental

# http://hastebin.com/          # no list of last pastes
# http://sebsauvage.net/paste/  # no list of last pastes
# http://tny.cz/                # no list of last pastes
# https://pastee.org/           # no list of last pastes
# http://paste2.org/            # no list of last pastes
# http://0bin.net/              # no list of last pastes
# http://markable.in/           # no list of last pastes


#####
# Configuration section to configure proxies
# Currently only HTTP proxies are permitted
#
proxy:
#  use: yes
  random: no
  single-proxy: 'http://127.0.0.1:8080'
#  random-proxy-file: 'proxies.txt'

#####
# Configuration section for User-Agents
#
user-agent:
  random: yes
  file: 'user-agents.txt'

**Comment by cvandeplas** [comment]
Do you still have this problem with the latest commit?

**Comment by turtle977** [comment]
I will check ASAP and let you know

**Comment by cvandeplas** [comment]
Any update here?
