### ISSUE TITLE
pystemon not receiving any matches

### ISSUE THREAD

**Issue by anishmi123** [cvandeplas/pystemon#54]
Hi,

Thanks for the great tool. However, I have been running the tool for sometime now but I cant seem to get any matches.

It is downloading the pasties but the alerts folder is still empty and i have not received a single match from any of the websites. The regex are as simple as searching for the word function just to test and still no matches.

Could you please help ?

**Comment by cvandeplas** [comment]
Hello there,

Have you tried enabling the save-all ? 
If yes, Is the archive folder filling with real content of pasties? (check manually)

**Comment by anishmi123** [comment]
Yes.. Sharing the config file for your reference.

The archive folder is filling with content of the pasties but not for the sites pastie.org and codepad.org.


Note : Changed file name to .txt from .yaml.

[pystemon.txt](https://github.com/cvandeplas/pystemon/files/242401/pystemon.txt)

**Comment by anishmi123** [comment]
Hi,

Any news on this ??

On Friday, April 29, 2016, Christophe Vandeplas <notifications@github.com>
wrote:

> Hello there,
>
> Have you tried enabling the save-all ?
> If yes, Is the archive folder filling with real content of pasties? (check
> manually)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/cvandeplas/pystemon/issues/54#issuecomment-215683927>
>


-- 
Regards,
Anish Mitra

**Comment by anishmi123** [comment]
Hi,

Can you please help me.....

**Comment by cvandeplas** [comment]
Some remarks: 
- You have both pastebin as pastebin_pro enabled. This is not recommended. 
- You have one uppercase 'SEARCH' this should be lowercase
- You have one entry with no 'search' word, ( `- description: 'Download (non-porn)'`)  that results in a `keyerror` error.  Comment that out.
- The codepad seems to work on my computer
- A good advice is : When encountering problems with specific sites, disable all the other sites and enable verbose output. Then try to understand what is going wrong. Also without verbose output I think the info is clearly visible: 
```
[2016-05-04 10:49:02,210] No last pasties matches for regular expression site:pastie.org regex:<a href="http://pastie.org/pastes/(\d{7})">. Error in your regex? Dumping htmlPage 
```
This means that the originally provided regex is not working anymore...
Fortunately someone else already did a correction for the pastie site. I just merged the pull request. The new archive-regex should be: 
```
    archive-regex: '<a href="http://pastie.org/pastes/(\d+)">'
```

**Comment by anishmi123** [comment]
Hey,

Thanks a ton for the remarks. It was a bit stupid on my part to overlook the upper case search. Thanks for the help on pastie.org too.. I hadnt noticed that the regex was out of date.

The issue is now resolved. Thanks again.

:)

Regards,
Anish
