### ISSUE TITLE
Regex Match Email Addresses

### ISSUE THREAD

**Issue by diogo-fernan** [cvandeplas/pystemon#59]
There seems to be a bug with regex pattern matching for email addresses when the regex pattern is set to search only for the domain, as in the following example:
- search: 'domain.com'

If a paste contains "email@domain.com", no match is triggered.
Tested on different paste websites.

Can you replicate this issue?

**Comment by Deventual** [comment]
Hi there,

It's very simple,
Try this way:
search: 'domain\\.com'

**Comment by diogo-fernan** [comment]
Still does not work.

The following is what happens.

The creation of a new paste with `domain.com` triggers for the regex expression `(domain|domain2)\\.com`.
However, the creation of a new paste with `1@domain.com` does not trigger for the same regular expression.

Notwithstanding, the `re.findall()` function (the same one used by pystemon) returns matches for both cases via the Python interactive console.

Can you reproduce this behavior?

**Comment by Deventual** [comment]
You can try using my fork which support regex through json config file,
I can approve it is fully working.

**Comment by cvandeplas** [comment]
Can you confirm you still have this issue? I'm curious as I was never able to reproduce this behavior.

**Comment by diogo-fernan** [comment]
Seems to be working! :-)
