### ISSUE TITLE
Python 3 Support 

### ISSUE THREAD

**Issue by Hallec** [cvandeplas/pystemon#64]
Hi,

Probably I am absolutely wrong, but I have detected a possible issue in pystemon.py (specifically the fork in circl repository, after adding Python 3 support). The problems are in lines: 329 and 338, when variable named: description is a list, it is not possible to use the function decode, because decode it is for binary data. When trying to decode in a list, and error is raised, so I think the solution is this:
replacing: return '[{}]'.format(', '.join(descriptions.decode('utf-8', 'ignore')))
with: return '[{}]'.format(', '.join(descriptions))

For line 339, the same procedure.

If I am wrong, sorry I am just trying to help.

Thank you very much for continuing the development of this project.

**Comment by cvandeplas** [comment]
The current version of pystemon was merged with most of the changes from the AIL fork.
