### ISSUE TITLE
pastebin.ca regex error

### ISSUE THREAD

**Issue by j-marz** [cvandeplas/pystemon#68]
`No last pasties matches for regular expression site:pastebin.ca regex:rel="/preview.php\?id=(\d+). Error in your regex? Dumping htmlPage #012 <?xml version="1.0" encoding="utf-8"?>#012<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">#012<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="" lang="">#012<head>#012    <title>pastebin - Type, paste, share.</title>#012    <meta name="microid" content="ca0462a24e49b118730aa3ba02c4e6cc5a55cd2d"/>#012    <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>#012     <script type="text/javascript">#012//<![CDATA[#012try{if (!window.CloudFlare) {var CloudFlare=[{verbose:0,p:0,byc:0,owlid:"cf",bag2:1,mirage2:0,oracle:0,paths:{cloudflare:"/cdn-cgi/nexp/dok3v=1613a3a185/"},atok:"562c088a39c1bb7971cde1dfe7a5cc2a",petok:"015d3265ec133392a1e4c2c915eb50a5492261f3-1491187013-1800",zone:"pastebin.ca",rocket:"m",apps:{}}];document.write('<script type="text/javascript" src="//ajax.cloudflare.com/cdn-cgi/nexp/dok3v=f2befc48d1/cloudflare.min.js"><'+'\/script>');}}catch(e){};#012//]]>#012</script>#012<link rel="stylesheet" href="https://pastebin.ca/pb-g.css" type="text/css"/>#012        <link rel="icon" href="https://pastebin.ca/pastebin.ico" type="image/x-icon"/>#012        <link rel="shortcut icon" href="https://pastebin.ca/pastebin.ico"#012              type="image/x-icon"/>#012                <link rel="alternate" href="http://en.pastebin.ca/"#012              hreflang="en" title="English Translation"/>#012        <link rel="alternate" href="http://fr.pastebin.ca/"#012              hreflang="fr" title="French Translation"/>#012        <link rel="alternate" href="http://de.pastebin.ca/"#012              hreflang="de" title="German Translation"/>#012        <link rel="alternate" href="http://ja.pastebin.ca/"#012              hreflang="ja" title="Japanese Translation"/>#012        <link href="mailto:admin@pastebin.ca" rev="made"/>#012    <link rel="alternate" type="application/rss+xml" title="Posts" href="/rss/posts.rss"/>#012    <link rel="alternate" type="application/rss+xml" title="News" href="/rss/news.rss"/>#012    <link rel="Help" href="/what.php"/>#012    <script type="text/javascript" src="https://code.jquery.com/jquery-1.12.4.min.js"></script>#012    <script type="text/javascript" src="https://code.jquery.com/ui/1.12.0/jquery-ui.min.js"></script>#012    <script type="text/javascript" src="/jquery.cluetip.min.js"></script>#012    <script src="https://pastebin.ca/pb-h.js?2" type="text/javascript"></script>#012<script type="text/javascript" async src="https://www.google.com/recaptcha/api.js"></script>#012<script type="text/javascript">#012  var _paq = _paq || [];#012  _paq.push(["setDomains", ["*.pastebin.ca"]]);#012  _paq.push(['trackPageView']);#012  _paq.push(['enableLinkTracking']);#012  (function() {#012    var u="//pw.vocti.ca/";#012    _paq.push(['setTrackerUrl', u+'piwik.php']);#012    _paq.push(['setSiteId', '3']);#012    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];#012    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);#012  })();#012</script>#012</head>#012<body>#012        <div id="header">#012            <h1><span style="color:#003366">paste</span>bin - Type, paste, share.</h1>#012        </div>#012            <div id="grprun">Part of <a href="http://slepp.ca/">Slepp's Projects</a> &mdash; <a href="http://pastebin.ca/">Pastebin</a> &mdash;#012            <a href="http://turl.ca/">TURL</a> &mdash; <a href="http://imagebin.ca/">Imagebin</a> &mdash; <a#012                href="http://filebin.ca/">Filebin</a></div>#012        <div id="runner"><a href="/feedback.php">Feedback</a> --#012                            <a href="http://en.pastebin.ca/"#012                   class="sprite sprite-ca">English</a>#012                <a href="http://fr.pastebin.ca/"#012                   class="sprite sprite-fr">French</a>#012                <a href="http://de.pastebin.ca/"#012                   class="sprite sprite-de">German</a>#012                <a href="http://ja.pastebin.ca/"#012                   class="sprite sprite-jp">Japanese</a>#012                    </div>#012        <script type="text/javascript">showRunnerMenu();</script>#012        <form method="get" action="/search.php">#012            <div id="topmenu"><a href="new.php" title="Create a new Paste|Follow this link to create a brand new paste."#012                                 class="jt">Create</a> <a href="upload.php"#012                                                          title="Upload Text, Images or Files|By following this link, you can upload a a text or source file, upload an image, or upload a file!"#012                                                          class="jt">Upload</a> <a href="newest.php">Newest</a> <a#012                    href="tools.php">Tools</a> <a href="donate.php">Donate</a> <input type="text" name="q"#012                                                                                      size="10"/><input type="submit"#012                                                                                                        value="Go"/>#012            </div>#012        </form>#012        <div id="body">#012    <div id="sl"><div class="bl"><div class="br"><div class="tl"><div class="tr"><div class="menu" id="idmenu0"><div class="menutitle"><h2>Stuff to Do</h2></div><div class="items" id="idmenu0-collapse"><div class="link"><a href="/new.php" class="sprite sprite-tab_new">New Post</a>#012</div>#012<div class="link"><a href="/upload.php" class="sprite sprite-top">Upload a Post</a>#012</div>#012<div class="link"><a href="/newest.php" class="sprite sprite-recur">Goto Newest</a>#012</div>#012<div class="link"><a href="/search.php" class="sprite sprite-search">Search</a>#012</div>#012<div class="link"><a href="/tools.php" class="sprite sprite-runprog">Tools / APIs</a>#012</div>#012<div class="link"><a href="/donate.php" class="sprite sprite-emoticon">Donate</a>#012</div>#012</div>#012</div>#012<div class="menu" id="idmenu1"><div class="menutitle"><h2>Information</h2></div><div class="items" id="idmenu1-collapse"><div class="link"><a href="/news.php" class="sprite sprite-comment">Site News</a>#012</div>#012<div class="link"><a href="/what.php" class="sprite sprite-documentinfo">What is This?</a>#012</div>#012</div>#012</div>#012#012    <div class="menu" id="id2243084">#012        <div class="menutitle">#012            <h2>Quick Search</h2>#012        </div>#012#012        <div id="id2243084-collapse">#012            <form method="get" action="/search.php">#012                <fieldset id="searchbar" class="searchbar">#012                    <input type="text" name="q" size="15" style="width:10em" class="input-box"/>#012                    <br/>#012                    <input type="submit" value="Search" class="submit-button"#012                           onclick="this.value='Searching...'"/>#012                    <br/>#012                </fieldset>#012            </form>#012            <form action="http://pastebin.ca/google.php" id="cse-search-box">#012                <fieldset id="googlebar" class="searchbar">#012                    <input type="hidden" name="cx" value="partner-pub-0367252804969302:1yimxphzru5"/>#012                    <input type="hidden" name="cof" value="FORID:10"/>#012                    <input type="hidden" name="ie" value="UTF-8"/>#012                    <input type="text" name="q" id="sbi" style="width:10em" class="input-box"/>#012                    <input type="submit" name="sa" value="Google Search" id="sbb" class="submit-button"/>#012                </fieldset>#012            </form>#012        </div>#012    </div>#012        <div class="menu" id="idmenurecent">#012        <div class="menutitle"><h2>Recent Posts</h2></div>#012        <div class="items" id="idmenurecent-collapse">#012            </div></div></div></div></div></div></div><div id="content"><div style="text-align:center;width:100%;ba`

**Comment by cvandeplas** [comment]
The pastebin.ca website returns a `503 Service Unavailable` error now.
The site configuration has been commented out from the `pystemon.yaml` configuration file.
