### ISSUE TITLE
string indices must be integers, not str

### ISSUE THREAD

**Issue by dev-forum-livre** [cvandeplas/pystemon#73]
Hello,
Any help with the following error would be appreciated:
ThreadPasties for pastebin.com_pro crashed unexpectectly, recovering...: string indices must be integers, not str

My IP address is already whitelisted on pastebin.
Thank you.

**Comment by cvandeplas** [comment]
Hi Jose,

Weird, I have not been experiencing this.
Are you using proxies?

The best is to disable all paste-sites, and enable debugging.    at line 951 (or so) change  logger.setLevel(logging.INFO)  to     logger.setLevel(logging.DEBUG)
You should then see a full stacktrace when it crashes.

**Comment by cvandeplas** [comment]
problem was caused by a mistake in the yaml file.
