### ISSUE TITLE
No such file or Directory

### ISSUE THREAD

**Issue by MrDoubts** [cvandeplas/pystemon#75]
Some minutes after launching the feeder it gives this error and everything stops:

Traceback (most recent call last):
File "pystemon-feeder.py", line 64, in
messagedata = open(pystemonpath+paste).read()
IOError: [Errno 2] No such file or directory: '/home/gt/pystemon/archive/codepad.org/2018/01/03/8RsQZOlJ.gz'

The directory doesn't really exist and I made a FLUSHALL to redis but the problem persists.

Any idea?
Thanks,

**Comment by cvandeplas** [comment]
```pystemon-feeder.py``` is part of the [AIL](https://github.com/CIRCL/AIL-framework) project. So their issue tracking might be the best for this question/issue.
But looking at the error you get I would indeed expect a discrepancy between the paths where ```pystemon``` stores the pastes and where ```pystemon-feeder.py``` tries to get it. Are you sure that your AIL config has ```pystemonpath``` configured properly?
