### ISSUE TITLE
Error importing BeautifulSoup

### ISSUE THREAD

**Issue by TheRealBards** [cvandeplas/pystemon#78]
Hi,

Nothing major but if you do an update for bug fixes at some point.

It throws an error when running Pystemon. 
ERROR: Cannot import the BeautifulSoup 3 Python library. Are you sure you installed it?

This is due to the import being:
from BeautifulSoup import BeautifulSoup

BS4 uses:
from bs4 import BeautifulSoup

Thanks,

**Comment by cvandeplas** [comment]
Actually, it's because pystemon requires BS3, not version 4. 
The new, python3, version will definitely use BS4...
Thanks for the remark though

**Comment by TheRealBards** [comment]
Sorry, it's just that the requirements.txt installs bs4

```
PyYAML
BeautifulSoup4
```

**Comment by cvandeplas** [comment]
oh OK.
Well, the current version is now using BS4 so that's fixed :-)
