### ISSUE TITLE
pastebin - scrape API URL change

### ISSUE THREAD

**Issue by AndreC10002** [cvandeplas/pystemon#79]
The current URLs of the scraping API of pastebin will be discontinued on 2018-04-27.  Details about the new address(es) are available at:

https://pastebin.com/doc_scraping_api

The file pystemon.yaml needs to be modifying accordingly.  My understand is that all they did was add the host name 'scrape' to the API URLs.

**Comment by cvandeplas** [comment]
thank you, this has been implemented in https://github.com/cvandeplas/pystemon/commit/8909571be04daf7a4d967c7bf001878fe33ee50e
