### ISSUE TITLE
Pastebin_Pro has updated their scraping URLs.  Use the following configuration

### ISSUE THREAD

**Issue by logikphreak** [cvandeplas/pystemon#82]
pastebin.com_pro:
    archive-url: 'https://scrape.pastebin.com/api_scraping.php?limit=100'
    archive-regex: '"key": "(.+)",'
    download-url: 'https://scrape.pastebin.com/api_scrape_item.php?i={id}'
    public-url: 'https://pastebin.com/raw/{id}'
    update-max: 20
    update-min: 10

**Comment by cvandeplas** [comment]
Thank you for the feedback.
This new URL format is already in place: https://github.com/cvandeplas/pystemon/blob/master/pystemon.yaml#L95

Don't hesitate to reopen if there's a problem or a typo somewhere.
