### ISSUE TITLE
HTTPlib error proxy error http://pastie.org/pastes

### ISSUE THREAD

**Issue by trismegistusX** [cvandeplas/pystemon#92]
Hoping this is just temporary issue as just setup pystemon up:

Error 521 Ray ID: 4508f07cc11ba6d7 • 2018-08-26 
Web server is down

`Failed to download the page because of other HTTPlib error proxy error http://pastie.org/pastes trying again.
[2018-08-26 ] Retry 1/100 for http://pastie.org/pastes
[2018-08-26 ] Failed to download the page because of other HTTPlib error proxy error http://pastie.org/pastes trying again.
`

Is this a regular issue with the above website?

**Comment by timhux123** [comment]
Seeing the same error on a new install but with pastebin.com/archive. I'm using the default configuration and paste from slexy and codebase are working successfully. From time to time a few of the paste from pastebin are successful.

**Comment by SteveClement** [comment]
pastie.org is down.
Can be closed.

**Comment by cvandeplas** [comment]
Yes, and that part is commented out in a section clearly marked as "websites are down".
