### ISSUE TITLE
Pastebin_Pro - Error in your regex

### ISSUE THREAD

**Issue by timhux123** [cvandeplas/pystemon#93]
Signed up and received a pastebin pro account and receive the error below after adding the Developer API Key to the configuration.
The feed dumps the paste to the screen and does not add them to AIL.
Slexy and codepad feeds are working successfully. The issue is only with the pastebin pro config.

"No last pasties matches for regular expression site:pastebin.com_pro regex:"123456790ABCDEFGHIJ": "(.+)",. Error in your regex? Dumping htmlPage"

My pastebin.com pro account configuration in pystemon.yaml:

  pastebin.com_pro:
    archive-url: 'https://scrape.pastebin.com/api_scraping.php?limit=500'
    archive-regex: '"123456790ABCDEFGHIJ": "(.+)",'
    download-url: 'https://scrape.pastebin.com/api_scrape_item.php?i={id}'
    public-url: 'https://pastebin.com/raw/{id}'
    update-max: 50
    update-min: 40

**Comment by cvandeplas** [comment]
You should not change the regex in the yaml. Normally pastebin allows you
to whitelist your public IP. No API key needs to be added to the yaml file.

Did this behaviour change? See the URL given in the yaml file pointing to
the page where you can whitelist your IP.

Unfortunately I barely have access to the web for two weeks and can't have
a look myself to check if things changed.

**Comment by timhux123** [comment]
Thanks for the pointers! You are correct, I was under the impression the "key" value in the regex was a place holder for your own pastebin api key. I changed the pastebin pro config in the yaml file back to the default and white listed my IP. All working now.
