### ISSUE TITLE
Proxy Question

### ISSUE THREAD

**Issue by timhux123** [cvandeplas/pystemon#97]
AIL version 1.6
Ubuntu 16.04

I'm trying to use a proxy for pystemon. The question is how do you specify the proxy settings? I see at the bottom of the pystemon.yaml file there is the following proxy configuration:

proxy:
  random: no
  file: 'proxies.txt'

I added my proxy address in the proxies.txt file but this did not help.

**Comment by cvandeplas** [comment]
Set `random` to `yes`, and only have 1 proxy in your `proxies.txt` file. 
It's true that the random word is confusing if you only use one proxy.

**Comment by timhux123** [comment]
Thanks! The steps you provided did the job.
